include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/graphql/**

linter:
  rules:
     prefer_const_constructors : false
     sized_box_for_whitespace : false
     sort_pub_dependencies : false