name: eiga
description: Anilist Client with extra oomph.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.0.0-nullsafety.2
  http: ^0.13.1
  html: ^0.15.0
  android_intent: ^2.0.0
  oauth2_client: ^2.0.1
  cached_network_image: ^3.0.0
  expandable_text: ^2.0.0
  intl: ^0.17.0
  carousel_slider: ^4.0.0-nullsafety.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^7.0.0-beta.3
  build_runner: '>=1.10.4'
  json_serializable: ^4.1.0
  lint: ^1.5.3

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Regular.ttf
        #           weight: 400
        - asset: lib/assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Rubik-Black.ttf
          weight: 900

