name: eiga
description: Anilist Client with extra oomph.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: '>=1.0.0'
  graphql_flutter: '>=3.0.0'
  http: '>=0.12.2'
  html: '>=0.15.0'
  android_intent: '>=0.3.7+7'
  oauth2_client: '>=1.6.1'
  cached_network_image: '>=2.5.0'
  expandable_text: ^2.0.0-nullsafety.1
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: '>=6.0.0 <7.0.0'
  build_runner: '>=1.10.4'
  json_serializable: '>=3.5.0'
  lint: ^1.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik-Regular.ttf
        #           weight: 400
        - asset: lib/assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Rubik-Black.ttf
          weight: 900

