name: eiga
description: Anilist Client with extra oomph.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent: ^2.0.0
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  expandable_text: ^2.0.0
  fl_chart: ^0.35.0
  flutter_inappwebview: ^5.3.2
  graphql_flutter: ^5.0.0-nullsafety.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  html: ^0.15.0
  http: ^0.13.1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  oauth2_client: ^2.0.1
  share: ^2.0.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^7.0.0-beta.3
  build_runner: ^2.0.3
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  hive_generator: ^1.1.0
  json_serializable: ^4.1.0
  lint: ^1.5.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-VariableFont_slnt,wght.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/icon.png"
  adaptive_icon_foreground: "lib/assets/icon.png"
  adaptive_icon_background: "#000000"

flutter_native_splash:
  color: "#000000"
  image: "lib/assets/splash.png"
  android: true
